// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:convert' as _i26;
import 'dart:typed_data' as _i27;

import 'package:core/common/network_info.dart' as _i25;
import 'package:core/data/datasources/db/movie_database_helper.dart' as _i15;
import 'package:core/data/datasources/db/serial_database_helper.dart' as _i24;
import 'package:core/data/datasources/movie_local_data_source.dart' as _i13;
import 'package:core/data/datasources/movie_remote_data_source.dart' as _i11;
import 'package:core/data/datasources/serial_local_data_source.dart' as _i22;
import 'package:core/data/datasources/serial_remote_data_source.dart' as _i20;
import 'package:core/data/models/movie_detail_model.dart' as _i3;
import 'package:core/data/models/movie_model.dart' as _i12;
import 'package:core/data/models/movie_table.dart' as _i14;
import 'package:core/data/models/serial_detail_model.dart' as _i4;
import 'package:core/data/models/serial_model.dart' as _i21;
import 'package:core/data/models/serial_table.dart' as _i23;
import 'package:core/domain/entities/movie.dart' as _i9;
import 'package:core/domain/entities/movie_detail.dart' as _i10;
import 'package:core/domain/entities/serial.dart' as _i18;
import 'package:core/domain/entities/serial_detail.dart' as _i19;
import 'package:core/domain/repositories/movie_repository.dart' as _i6;
import 'package:core/domain/repositories/serial_repository.dart' as _i17;
import 'package:core/utils/failure.dart' as _i8;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i16;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeMovieDetailModel_1 extends _i1.Fake implements _i3.MovieDetailModel {
}

class _FakeSerialDetailModel_2 extends _i1.Fake
    implements _i4.SerialDetailModel {}

class _FakeResponse_3 extends _i1.Fake implements _i5.Response {}

class _FakeStreamedResponse_4 extends _i1.Fake implements _i5.StreamedResponse {
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i6.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i2.Either<_i8.Failure, _i10.MovieDetail>>.value(
              _FakeEither_0<_i8.Failure, _i10.MovieDetail>())) as _i7
          .Future<_i2.Either<_i8.Failure, _i10.MovieDetail>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveMovieWatchlist(
          _i10.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveMovieWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>()))
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeMovieWatchlist(
          _i10.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMovieWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>()))
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<bool> isAddedToMovieWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToMovieWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.Movie>>> getWatchlistMovie() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovie, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>.value(
              _FakeEither_0<_i8.Failure, List<_i9.Movie>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i9.Movie>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i11.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i12.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
              returnValue:
                  Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
          as _i7.Future<List<_i12.MovieModel>>);
  @override
  _i7.Future<List<_i12.MovieModel>> getPopularMovies() => (super.noSuchMethod(
          Invocation.method(#getPopularMovies, []),
          returnValue: Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
      as _i7.Future<List<_i12.MovieModel>>);
  @override
  _i7.Future<List<_i12.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
          Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
      as _i7.Future<List<_i12.MovieModel>>);
  @override
  _i7.Future<_i3.MovieDetailModel> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue:
                  Future<_i3.MovieDetailModel>.value(_FakeMovieDetailModel_1()))
          as _i7.Future<_i3.MovieDetailModel>);
  @override
  _i7.Future<List<_i12.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
          as _i7.Future<List<_i12.MovieModel>>);
  @override
  _i7.Future<List<_i12.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
          as _i7.Future<List<_i12.MovieModel>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i13.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertMovieWatchlist(_i14.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertMovieWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<String> removeMovieWatchlist(_i14.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMovieWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i14.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i14.MovieTable?>.value())
          as _i7.Future<_i14.MovieTable?>);
  @override
  _i7.Future<List<_i14.MovieTable>> getWatchlistMovies() => (super.noSuchMethod(
          Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<List<_i14.MovieTable>>.value(<_i14.MovieTable>[]))
      as _i7.Future<List<_i14.MovieTable>>);
  @override
  _i7.Future<void> cacheNowPlayingMovies(List<_i14.MovieTable>? movies) =>
      (super.noSuchMethod(Invocation.method(#cacheNowPlayingMovies, [movies]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<List<_i14.MovieTable>> getCachedNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getCachedNowPlayingMovies, []),
              returnValue:
                  Future<List<_i14.MovieTable>>.value(<_i14.MovieTable>[]))
          as _i7.Future<List<_i14.MovieTable>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MovieDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDatabaseHelper extends _i1.Mock
    implements _i15.MovieDatabaseHelper {
  MockMovieDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i16.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i16.Database?>.value())
          as _i7.Future<_i16.Database?>);
  @override
  _i7.Future<void> insertMovieCacheTransaction(
          List<_i14.MovieTable>? movies, String? category) =>
      (super.noSuchMethod(
          Invocation.method(#insertMovieCacheTransaction, [movies, category]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheMovies, [category]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  _i7.Future<int> clearMovieCache(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearMovieCache, [category]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> insertMovieWatchlist(_i14.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertMovieWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> removeMovieWatchlist(_i14.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMovieWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SerialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialRepository extends _i1.Mock implements _i17.SerialRepository {
  MockSerialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Serial>>> getOnTheAirSerials() =>
      (super.noSuchMethod(Invocation.method(#getOnTheAirSerials, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Serial>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Serial>>> getPopularSerials() =>
      (super.noSuchMethod(Invocation.method(#getPopularSerials, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Serial>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Serial>>> getTopRatedSerials() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedSerials, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Serial>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, _i19.SerialDetail>> getSerialDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getSerialDetail, [id]),
          returnValue: Future<_i2.Either<_i8.Failure, _i19.SerialDetail>>.value(
              _FakeEither_0<_i8.Failure, _i19.SerialDetail>())) as _i7
          .Future<_i2.Either<_i8.Failure, _i19.SerialDetail>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>
      getSerialRecommendations(int? id) => (super.noSuchMethod(
          Invocation.method(#getSerialRecommendations, [id]),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Serial>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Serial>>> searchSerials(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchSerials, [query]),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Serial>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveSerialWatchlist(
          _i19.SerialDetail? serial) =>
      (super.noSuchMethod(Invocation.method(#saveSerialWatchlist, [serial]),
              returnValue: Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>()))
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeSerialWatchlist(
          _i19.SerialDetail? serial) =>
      (super.noSuchMethod(Invocation.method(#removeSerialWatchlist, [serial]),
              returnValue: Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>()))
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<bool> isAddedToSerialWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToSerialWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Serial>>> getWatchlistSerial() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistSerial, []),
          returnValue: Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>.value(
              _FakeEither_0<_i8.Failure, List<_i18.Serial>>())) as _i7
          .Future<_i2.Either<_i8.Failure, List<_i18.Serial>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SerialRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialRemoteDataSource extends _i1.Mock
    implements _i20.SerialRemoteDataSource {
  MockSerialRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i21.SerialModel>> getOnTheAirSerials() =>
      (super.noSuchMethod(Invocation.method(#getOnTheAirSerials, []),
              returnValue:
                  Future<List<_i21.SerialModel>>.value(<_i21.SerialModel>[]))
          as _i7.Future<List<_i21.SerialModel>>);
  @override
  _i7.Future<List<_i21.SerialModel>> getPopularSerials() =>
      (super.noSuchMethod(Invocation.method(#getPopularSerials, []),
              returnValue:
                  Future<List<_i21.SerialModel>>.value(<_i21.SerialModel>[]))
          as _i7.Future<List<_i21.SerialModel>>);
  @override
  _i7.Future<List<_i21.SerialModel>> getTopRatedSerials() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedSerials, []),
              returnValue:
                  Future<List<_i21.SerialModel>>.value(<_i21.SerialModel>[]))
          as _i7.Future<List<_i21.SerialModel>>);
  @override
  _i7.Future<_i4.SerialDetailModel> getSerialDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getSerialDetail, [id]),
              returnValue: Future<_i4.SerialDetailModel>.value(
                  _FakeSerialDetailModel_2()))
          as _i7.Future<_i4.SerialDetailModel>);
  @override
  _i7.Future<List<_i21.SerialModel>> getSerialRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getSerialRecommendations, [id]),
              returnValue:
                  Future<List<_i21.SerialModel>>.value(<_i21.SerialModel>[]))
          as _i7.Future<List<_i21.SerialModel>>);
  @override
  _i7.Future<List<_i21.SerialModel>> searchSerials(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchSerials, [query]),
              returnValue:
                  Future<List<_i21.SerialModel>>.value(<_i21.SerialModel>[]))
          as _i7.Future<List<_i21.SerialModel>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SerialLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialLocalDataSource extends _i1.Mock
    implements _i22.SerialLocalDataSource {
  MockSerialLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertSerialWatchlist(_i23.SerialTable? serial) =>
      (super.noSuchMethod(Invocation.method(#insertSerialWatchlist, [serial]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<String> removeSerialWatchlist(_i23.SerialTable? serial) =>
      (super.noSuchMethod(Invocation.method(#removeSerialWatchlist, [serial]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i23.SerialTable?> getSerialById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getSerialById, [id]),
              returnValue: Future<_i23.SerialTable?>.value())
          as _i7.Future<_i23.SerialTable?>);
  @override
  _i7.Future<List<_i23.SerialTable>> getWatchlistSerials() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistSerials, []),
              returnValue:
                  Future<List<_i23.SerialTable>>.value(<_i23.SerialTable>[]))
          as _i7.Future<List<_i23.SerialTable>>);
  @override
  _i7.Future<void> cacheOnTheAirSerials(List<_i23.SerialTable>? serials) =>
      (super.noSuchMethod(Invocation.method(#cacheOnTheAirSerials, [serials]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<List<_i23.SerialTable>> getCachedOnTheAirSerials() =>
      (super.noSuchMethod(Invocation.method(#getCachedOnTheAirSerials, []),
              returnValue:
                  Future<List<_i23.SerialTable>>.value(<_i23.SerialTable>[]))
          as _i7.Future<List<_i23.SerialTable>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SerialDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialDatabaseHelper extends _i1.Mock
    implements _i24.SerialDatabaseHelper {
  MockSerialDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i16.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i16.Database?>.value())
          as _i7.Future<_i16.Database?>);
  @override
  _i7.Future<void> insertSerialCacheTransaction(
          List<_i23.SerialTable>? serials, String? category) =>
      (super.noSuchMethod(
          Invocation.method(#insertSerialCacheTransaction, [serials, category]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheSerials(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheSerials, [category]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  _i7.Future<int> clearSerialCache(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearSerialCache, [category]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> insertSerialWatchlist(_i23.SerialTable? serial) =>
      (super.noSuchMethod(Invocation.method(#insertSerialWatchlist, [serial]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> removeSerialWatchlist(_i23.SerialTable? serial) =>
      (super.noSuchMethod(Invocation.method(#removeSerialWatchlist, [serial]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getSerialById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getSerialById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistSerials() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistSerials, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i25.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i26.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i26.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i26.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i26.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i27.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i27.Uint8List>.value(_i27.Uint8List(0)))
          as _i7.Future<_i27.Uint8List>);
  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4()))
          as _i7.Future<_i5.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
